name: "Sphinx: Render docs"

on: 
  pull_request:
    branches:
      - 'main'

env:
  GIT_USER_NAME: BattINFO Developers
  GIT_USER_EMAIL: "BattINFO@big-map.org"
    
jobs:
  updatepages:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read  # Set to read to prevent pushing changes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Replace with the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Markdown==3.4.3 rdflib==6.3.2 pandoc  # Add any other dependencies if needed
        
    - name: Render documentation from ttl
      run: python docs/scripts/ttl_to_rst.py

    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "apt-get update -y; apt-get install -y pandoc"

    - name: Check if HTML context directory exists
      run: |
        if [ ! -d "docs/_build/html/version/" ]; then
          echo "Creating HTML versions directory"
          sudo mkdir -p docs/_build/html/version/
        else
          echo "HTML version directory already exists"
        fi

    - name: Fetch all tags and create version directories
      run: |
        git fetch --tags
        git tag | while read TAG; do
          sudo mkdir -p "docs/_build/html/version/$TAG"
          sudo cp "bigmap.ttl" "docs/_build/html/version/$TAG/"
        done

    # Removed the push and deploy steps as they should not run on PRs to master
